---
title: "Plots"
output: html_document
date: "2022-09-22"
---

```{r include=F}
library(dplyr)
library(ggplot2)
library(knitr)
knitr::opts_knit$set(progress = FALSE, verbose = FALSE)
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

<center>
# Hogy is volt ez a Messengeren? 
</center>

## Több mint 6 év üzenetváltása
### Ajesz 2022
Blabla

```{r napi_adat}
d1 <- data %>% 
  group_by(year,day) %>%
  count()
```

## Napi üzenetmennyiség
*2015.04.22. - 2022.09.17.*

```{r napi_plot, fig.width=11, fig.height=6}
ggplot(d1, aes(x=as.factor(day), y=n, fill=as.factor(year))) + 
  geom_col() +
  theme_minimal() +
  theme(legend.position="bottom",legend.text = element_text(colour="#404040"),
    axis.title = element_blank(), plot.background = element_blank(),
    panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  scale_fill_brewer(palette = "Spectral",name="") +
  scale_x_discrete(breaks=c("2016-01-01","2017-01-01","2018-01-01","2019-01-02","2020-01-02","2021-04-01","2022-04-01"))
```


```{r end}
#options(knitr.duplicate.label = "allow")
knit2html("messages_output_v01.Rmd")
```

